<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{


    public function createNewCommentFromForm($user,$formData)
    {

		$newComment = $formData;
		$newComment->setUser($user);

        $em = $this->getEntityManager();
        $em->persist($newComment);
        $em->flush();

        return $newComment;
    }

}
