<?php

namespace AppBundle\Repository;

use Doctrine\ORM\ORMException;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{

    public function createNewTopicFromForm($user,$formData)
    {

  		try {

			$newTopic = $formData;
			$newTopic->setUser($user);

	        $em = $this->getEntityManager();
	        $em->persist($newTopic);
	        $em->flush();
        	
        	return $newTopic;

		} catch(ORMException $e) {
		    throw new ORMException('Can\'t insert entity.');
		}

    }


    public function findByCreatedAtOrder($order)
    {
        return $this->findBy(array(), array('createdAt' => $order));
    }

    public function getTopicsOrderedByNumberOfUpvotes()
	{
	    return $this->createQueryBuilder('topic')
	        ->addSelect('COUNT(upvotes) AS HIDDEN upvoteCount')
	        ->leftJoin('topic.upvotes', 'upvotes')
	        ->groupBy('topic')
	        ->orderBy('upvoteCount', 'DESC')
    		->getQuery()->getResult();

	}
}
