# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service

            access_denied_handler: AppBundle\Listener\AccessDeniedHandler
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout:
                path: /logout
                target: /login
                handlers: [app.logout.handler]

    access_control:
        - { path: ^/login$, allow_if: "not has_role('ROLE_USER')"}
        - { path: ^/register, allow_if: "not has_role('ROLE_USER')"  }